### ISSUE TITLE
MSRV bumped to 1.70

### ISSUE THREAD

**Issue by schungx** [matklad/once_cell#276]
The latest version bumps MSRV to Rust 1.70.0.

My repo happens to have MSRV of 1.66.0.  Is there a way to "lock" `once_cell` to version 1.20 such that it continues to work under 1.66?

I can see there is `Cargo.lock.msrv` but no idea how to use it in CI.

**Comment by matklad** [comment]
Run

```
cargo update once_cell --precise 1.20.3
```

inside of your repository and then make sure that Cargo.lock file indeed contains version v1.20.3 of once_cell, and that this Cargo.lock is committed to git.

**Comment by schungx** [comment]
I'm doing the msrv check in CI so I'm not very sure how to specify the lock file in such situation... any pointers?

I don't want to commit the lock file normally, only for CI check.

**Comment by matklad** [comment]
See https://github.com/matklad/once_cell/issues/201#issuecomment-1254883343 comment starting with “one practical problem”

**Comment by schungx** [comment]
Thanks to @matklad I now find an extremely simple method to deal with this in GitHub Actions.

1) Make a `Cargo.lock.msrv` locked to the MSRV.

2) Add the `run` line in `.github/build.yaml` (or any action):
```yaml
jobs:
  msrv:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
                    :
      - run: cp Cargo.lock.msrv Cargo.lock
                    :
```

3) Bob's your uncle!
